### ISSUE TITLE
500 Error at /job/new/ while creating a new job

### ISSUE THREAD

**Issue by stemmlerjs** [UnivJobs/univjobs-back#102]
Steps to produce error:
- 1.) Login as user nickcave@gmail.com
- 2.) Select Summer Job on  /catagories
- 3.) Fill out and complete form to create a new job
- 4.) 500 Server Error

**AttributeError at /api/job/new/
'dict' object has no attribute 'dict'
Request Method: POST
Request URL:    http://ec2-52-87-227-85.compute-1.amazonaws.com:8000/api/job/new/
Django Version: 1.9.7
Exception Type: AttributeError
Exception Value:  
'dict' object has no attribute 'dict'
Exception Location: /home/ec2-user/univjobs-back/univjobs/job/views.py in post, line 93
Python Executable:  /usr/bin/python34**

![image](https://cloud.githubusercontent.com/assets/6892666/19216326/de4afc12-8d84-11e6-8060-97333d0879a3.png)

**Comment by charlesjavelona** [comment]
**Note to self**
 This bug has been caused due to the changes in the db schema.

**Comment by charlesjavelona** [comment]
**Things to do at the backend:**
 - [ ] Create new api endpoint called /job/new/questions
 - [ ] Filter the most recent job id from jobs
 - [ ] Save the data into questions view

**Comment by charlesjavelona** [comment]
Done
