### ISSUE TITLE
As a developer I want to document our work automatically

### ISSUE THREAD

**Issue by charlesakio** [UnivJobs/univjobs-back#12]
# To Do:
-  [x] Auto Documentation of codes
-  [ ] Auto Documentation of tests
-  [ ] Auto Documentation of todo comment

**Comment by juliosueiras** [comment]
done for automation of doc, now for extra(test and other docs automation)

**Comment by juliosueiras** [comment]
**Update** this is almost completed(by using BDD style) and also I can direct edit issue and add issue from vim
so I don't have issue now for looking at your issues update =)
