### ISSUE TITLE
Add media directory for local development.

### ISSUE THREAD

**Issue by charlesakio** [UnivJobs/univjobs-back#57]
# Reference, Two scoops of Django, page 26

![screen shot 2015-07-17 at 11 01 34 am](https://cloud.githubusercontent.com/assets/7959179/8750047/39591d74-2c73-11e5-8d8e-6e66672df768.png)

**Comment by charlesakio** [comment]
![d_1210x804](https://cloud.githubusercontent.com/assets/7959179/8840730/35dba196-30b3-11e5-96d3-8322b0cf79a1.jpg)

**Comment by charlesakio** [comment]
![w-bspline](https://cloud.githubusercontent.com/assets/7959179/8842127/31bfe660-30c4-11e5-8f96-b7d79b9c6a64.jpg)

**Comment by juliosueiras** [comment]
??
