### ISSUE TITLE
OPTIONS Request in response to GET /account

### ISSUE THREAD

**Issue by stemmlerjs** [UnivJobs/univjobs-back#73]
OK @juliosueiras, @charlesakio; here's some fun HTTP stuff for us to figure out.

So right now, I'm working on verifying that the current user is authenticated on every route by checking the token. This should be a simple account /GET but *what happens when we add a custom header to the HTTP GET Request*? 

Found these resources below in the StackOverflow link I provided.
[Why am I getting an options request instead of a get request?](http://stackoverflow.com/questions/1256593/why-am-i-getting-an-options-request-instead-of-a-get-request)

I think it might be the header titled, **Authorization** that's requiring us to send an OPTIONS request before the GET request. And since the OPTIONS request strips out any headers, we keep on getting a 403 back from the server because the server is expecting it have the Authorization header for the OPTIONS method.

Also, from, https://bugs.jquery.com/ticket/12698,
_"It doesn't even seem to matter if you use POST or GET - the OPTIONS preflight request doesn't contain the "Authorization" header, thus ending in an unauthorized request to the server."_

Here is the culprit code that you can use to test that it's working or not. This will actually issue out an OPS

```javascript
var settings = {
  "async": true,
  "crossDomain": true,
  "url": "http://localhost:3000/api/account/",
  "method": "GET",
  "headers": {
    'Content-Type': 'text/plain',
    "authorization": "JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0NjkyMDg5MDksInVzZXJfaWQiOjEyLCJlbWFpbCI6ImtqaGtqZHNrYUBzaGVyaWRhbmNvbGxlZ2UuY2EiLCJ1c2VybmFtZSI6ImtqaGtqZHNrYUBzaGVyaWRhbmNvbGxlZ2UuY2EiLCJvcmlnX2lhdCI6MTQ2OTIwODYwOX0.ZN3Y4c6kpo2-GwhVcjP540Cp6zPEAeaOO7_TCut9ciM",
    "cache-control": "no-cache",
    "postman-token": "251b4e35-7975-aa58-8e1e-0c0e1bc2354c"
  },
  data: {
    'yo': 'yo'
  }
}

$.ajax(settings).done(function(result){
  console.log(result)
})
```

Runnable logs:

    [22/Jul/2016 17:31:21] "GET /me/ HTTP/1.1" 404 4282                                            
    [22/Jul/2016 17:31:27] "GET /api/account/ HTTP/1.1" 200 382                                    
    [22/Jul/2016 17:34:32] "GET /api/account/ HTTP/1.1" 403 58                                     
    [22/Jul/2016 17:36:44] "OPTIONS /api/register/ HTTP/1.1" 200 353                               
    [22/Jul/2016 17:36:45] "POST /api/register/ HTTP/1.1" 201 345                                  
    **[22/Jul/2016 17:37:02] "OPTIONS /api/account/ HTTP/1.1" 403 58**                                 
    [22/Jul/2016 17:41:17] "OPTIONS /api/register/ HTTP/1.1" 200 353                               
    [22/Jul/2016 17:41:17] "POST /api/register/ HTTP/1.1" 201 353                                  
    **[22/Jul/2016 17:41:29] "OPTIONS /api/account/ HTTP/1.1" 403 58**                                 
    [22/Jul/2016 17:48:25] "OPTIONS /api/register/ HTTP/1.1" 200 353                               
    [22/Jul/2016 17:48:26] "POST /api/register/ HTTP/1.1" 201 334                                  
    **[22/Jul/2016 17:48:43] "OPTIONS /api/account/ HTTP/1.1" 403 58**                                 
    [22/Jul/2016 17:49:39] "GET /api/account/ HTTP/1.1" 200 382                                    
    [22/Jul/2016 17:54:34] "OPTIONS /api/account/?yo=yo HTTP/1.1" 403 58                           
    [22/Jul/2016 17:55:18] "OPTIONS /api/account/?yo=yo HTTP/1.1" 403 58                           
    **[22/Jul/2016 17:55:23] "GET /api/account/?yo=yo HTTP/1.1" 403 4626**                             
    **[22/Jul/2016 17:56:47] "OPTIONS /api/account/?yo=yo HTTP/1.1" 403 58                           
    [22/Jul/2016 18:00:36] "OPTIONS /api/account/?yo=yo HTTP/1.1" 403 58**                           
    [22/Jul/2016 18:00:54] "GET /api/account/ HTTP/1.1" 200 382   

**So how do we fix it?**
The way I see it, we have two things we can experiment with:
1.) We override the OPTIONS method (which is just used for the server to trust that there aren't any erroneous custom fields) for the /account endpoint and pass back a 200 response EVEN if it doesn't contain a Authorization header.

2.) Use a default header value such as **x-access-token** (I think?). I used this as my auth token header name for when I was doing authorization on endpoints in SYNCt.

**Comment by charlesakio** [comment]
Im not familiar with this as much. Looking at it, I think #2 option would make sense because it takes less trip to the server to authenticate.

**Comment by stemmlerjs** [comment]
Right. Here's my equivalent Node.js code for authenticating. Notice that I'm using the x-access-token.

With this, I never had a problem.

```javascript
// ======================================================================================= //
// ================================= AUTHENTICATE MIDDLEWARE ============================= //
// =========================== Ensures that the user is authenticated on every request === //
// =========================== all requests past this point need authentication ========== //
// ======================================================================================= //
    
    // localhost:8080/* and everything else needs to be authorized
    
app.use(function (req, res, next) {    
    
    // Allow for token to be passed either via POST parameters, URL parameters, or HTTP header
    var token = req.body.token || req.query.token || req.headers['x-access-token'] || req.cookies.synctSessionToken;
    
    if (token) {
        jwt.verify(token, config.secret, function(err, decoded){
           if (err) {
               return res.status(403).send({ // 403 - forbidden
                   success: false,
                   message: 'Failed to Authenticate Token in REST call that requires token'
               });
           } else {
               // Set attribute on the request object so that when we pass this request through,
               // any Request will be able to tell if it is authenticated via if req.decoded != undefined
               req.decoded = decoded;
               
               next();
           }
        });
    } else {
        //Redirect to login if we cannot access any token witin cookie or header
        res.redirect('/login');
    }
});
```

**Comment by stemmlerjs** [comment]
Posting this here for reference:

These are the steps on how you can test to ensure that this is working.

1.) pull my code from the univjobs-front
2.) run node proxy.js
3.) Load up that code in a simple HTML page (it requires JQUERY)
4.) Test it out. It will proxy through port 3000

Here is something you can copy line for line. Just paste this in an html file and test it through the browser.

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <script src="https://code.jquery.com/jquery-3.0.0.min.js" integrity="sha256-JmvOoLtYsmqlsWxa7mDSLMwa6dZ9rrIdtrrVYRnDRH0=" crossorigin="anonymous"></script>
</head>
<body>
  <script>

var settings = {
  "async": true,
  "crossDomain": true,
  "url": "http://localhost:3000/api/account/",
  "method": "GET",
  "headers": {
    'Content-Type': 'text/plain',
    "authorization": "JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0NjkyMDg5MDksInVzZXJfaWQiOjEyLCJlbWFpbCI6ImtqaGtqZHNrYUBzaGVyaWRhbmNvbGxlZ2UuY2EiLCJ1c2VybmFtZSI6ImtqaGtqZHNrYUBzaGVyaWRhbmNvbGxlZ2UuY2EiLCJvcmlnX2lhdCI6MTQ2OTIwODYwOX0.ZN3Y4c6kpo2-GwhVcjP540Cp6zPEAeaOO7_TCut9ciM",
    "cache-control": "no-cache",
    "postman-token": "251b4e35-7975-aa58-8e1e-0c0e1bc2354c"
  },
  data: {
    'yo': 'yo'
  }
}

$.ajax(settings).done(function(result){
  console.log(result)
})
</script>
</body>
</html>


```

**Comment by juliosueiras** [comment]
Maybe we can use this?

https://github.com/ottoyiu/django-cors-headers/

**Comment by charlesakio** [comment]
We could, Im quite worried about how long this things is maintainable.

**Comment by stemmlerjs** [comment]
Always look for the easy fix without having to introduce layers of more code. I'd say look at that as a last resort.

**Comment by juliosueiras** [comment]
which is what I am doing, trying to see if there is way to fix that

**Comment by stemmlerjs** [comment]
Look at what they're doing and try to do it yourself without adding all of their code is what I'm saying.

**Comment by juliosueiras** [comment]
just double checking, does the issues happen in axios too?

**Comment by stemmlerjs** [comment]
Yes they do. You can try with it as well and should get the same result.

**Comment by juliosueiras** [comment]
Fix by adding [corsheader](https://github.com/ottoyiu/django-cors-headers) to django
