### ISSUE TITLE
API Semantics changes and security to user info

### ISSUE THREAD

**Issue by stemmlerjs** [UnivJobs/univjobs-back#74]
**Issue 1)**
Right now, a call to ```/api/account/``` returns every account in our application.
We should set this up so that only super user's can access this endpoint.

**Issue 2)** 
The naming scheme for /user/ and /account/
I think we decided before that we want to use /me for returning MY results for the currently authenticated user. Makes sense, lets go ahead and do this and change it from /user to /me.

I think /accounts should also be the name of the endpoint that returns all the accounts
and /me should be the name that returns only the authed user's info.

**Comment by charlesakio** [comment]
#74 resolved
