### ISSUE TITLE
/user needs to return isAStudent

### ISSUE THREAD

**Issue by stemmlerjs** [UnivJobs/univjobs-back#75]
Currently a call to ```/api/user/``` doesn't return isAStudent.
I need this be able to do auth routing.

**Comment by charlesakio** [comment]
#75 closed

**Comment by stemmlerjs** [comment]
This issue was resolved with the addition of two key attributes to the ```/api/me``` endpoint:

- is_a_student
- is_profile_completed

I can now determine the route that a user should be in based on these two attributes. Good work.
