### ISSUE TITLE
Documentation accuracy

### ISSUE THREAD

**Issue by stemmlerjs** [UnivJobs/univjobs-back#76]
For the ```/api/login/``` and other API endpoints, where it specifies the **parameters** required- it is actually the **body** that is required.

For example, the following request to ```/api/login/``` is unsuccessful as per current documentation:

**URL**: http://eoymxx-univjobs-back-staging-univjobs.runnableapp.com/api/login/
**Method:** POST
**Parameters:**
- username
- email
- password (REQUIRED)

**Body:** None

When in fact, it should be:

**URL**: http://eoymxx-univjobs-back-staging-univjobs.runnableapp.com/api/login/
**Method:** POST
**Parameters:** None
**Body (form-data):**
- username
- email
- password (REQUIRED)

**Comment by charlesakio** [comment]
I'll change this one tonight.

**Comment by charlesakio** [comment]
@stemmlerjs, is this related to the apiary docs?

**Comment by stemmlerjs** [comment]
@charlesakio, this is related to the Apiary Docs.
If you take a look at the documentation for this endpoint, you'll notice that it says the "username", "email" and "password" fields are to be specified in the _Parameters_ of the Request.

This is incorrect.

The endpoint actually reads these fields from the **Body**.
The documentation should reflect the _actual_ behavior.

**Comment by charlesakio** [comment]
#76 closed. 

Refer to Apiary [login docs](http://docs.univjobsback.apiary.io/#reference/user/login/login)
