### ISSUE TITLE
/logout should invalidate all current JWT tokens for the current user

### ISSUE THREAD

**Issue by stemmlerjs** [UnivJobs/univjobs-back#78]
Steps to produce error:
- Use /api/login to get JWT token.
- Use /api/me/ with JWT token as Authorization header
- Use /api/logout
- Use /api/me again with the same JWT token
- Results were returned for the user.

**Comment by charlesakio** [comment]
@stemmlerjs: Here are the [options](http://stackoverflow.com/questions/21978658/invalidating-json-web-tokens)

Option 1 makes sense for now because:
- It is the least amount of steps to do for now.
- Assuming that people will logout and won't go back in till the next time.

What say you?

**Comment by stemmlerjs** [comment]
Sure, lets just do that.
