### ISSUE TITLE
[Employers] PUT calls are throwing errors on api/me 

### ISSUE THREAD

**Issue by charlesjavelona** [UnivJobs/univjobs-back#82]
**Errors reported supplied by the same data**
```
  {
    "user": {
        "email": "businesstest1@gmail.com",
        "first_name": "Charles",
        "last_name": "Test",
        "mobile": "123456789",
        "date_joined": "2016-08-03T01:11:12.226938Z",
        "is_profile_completed": false,
        "is_a_student": false
    },
    "company_name": "Charles",
    "industry": 0,
    "logo": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Logo_TV_2015.png",
    "website": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Logo_TV_2015.png",
    "description": "This is a test",
    "employee_count": 3,
    "office_location": "2170 Bruns rd.",
    "office_city": "Oakville",
    "office_postal_code": "L5J4J2"
}
```

**Scenario 1:**
  Error:
```
HTTP 400 Bad Request
  Allow: GET, PUT, HEAD, OPTIONS
  Content-Type: application/json
  Vary: Accept
  
  {
    "logo": [
        "The submitted data was not a file. Check the encoding type on the form."
    ]
}
```
**Media type**
application/json
```
  {
    "user": {
        "email": "businesstest1@gmail.com",
        "first_name": "Charles",
        "last_name": "Test",
        "mobile": "123456789",
        "date_joined": "2016-08-03T01:11:12.226938Z",
        "is_profile_completed": false,
        "is_a_student": false
    },
    "company_name": "Charles",
    "industry": 0,
    "logo": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Logo_TV_2015.png",
    "website": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Logo_TV_2015.png",
    "description": "This is a test",
    "employee_count": 3,
    "office_location": "2170 Bruns rd.",
    "office_city": "Oakville",
    "office_postal_code": "L5J4J2"
}
```
<img width="1280" alt="screen shot 2016-08-03 at 10 45 43 pm" src="https://cloud.githubusercontent.com/assets/7959179/17388780/642333a0-59cc-11e6-9e6f-9f7f6c4490ee.png">

**Scenario 2**
Error:
```
HTTP 400 Bad Request
  Allow: GET, PUT, HEAD, OPTIONS
  Content-Type: application/json
  Vary: Accept
  
  {
    "company_name": [
        "This field is required."
    ],
    "user": [
        "This field is required."
    ]
}
```
**Media type**
application/x-www-form-urlencoded
```
  {
    "user": {
        "email": "businesstest1@gmail.com",
        "first_name": "Charles",
        "last_name": "Test",
        "mobile": "123456789",
        "date_joined": "2016-08-03T01:11:12.226938Z",
        "is_profile_completed": false,
        "is_a_student": false
    },
    "company_name": "Charles",
    "industry": 0,
    "logo": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Logo_TV_2015.png",
    "website": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Logo_TV_2015.png",
    "description": "This is a test",
    "employee_count": 3,
    "office_location": "2170 Bruns rd.",
    "office_city": "Oakville",
    "office_postal_code": "L5J4J2"
}
```

**Scenario 3**
Error:
```
HTTP 400 Bad Request
  Allow: GET, PUT, HEAD, OPTIONS
  Content-Type: application/json
  Vary: Accept
  
  {
    "detail": "Multipart form parse error - Invalid boundary in multipart: None"
}
```
**Media type**
multipart/form-data
```
  {
    "user": {
        "email": "businesstest1@gmail.com",
        "first_name": "Charles",
        "last_name": "Test",
        "mobile": "123456789",
        "date_joined": "2016-08-03T01:11:12.226938Z",
        "is_profile_completed": false,
        "is_a_student": false
    },
    "company_name": "Charles",
    "industry": 0,
    "logo": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Logo_TV_2015.png",
    "website": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Logo_TV_2015.png",
    "description": "This is a test",
    "employee_count": 3,
    "office_location": "2170 Bruns rd.",
    "office_city": "Oakville",
    "office_postal_code": "L5J4J2"
}
```

**Comment by charlesakio** [comment]
Seems to be the same issue at [Stackoverflow regarding Base64 ImageField](http://stackoverflow.com/questions/28036404/django-rest-framework-upload-image-the-submitted-data-was-not-a-file). 

Will test first on supplying the same data to multiform/form-data.
If that does not work. Will have to implement a Class Based View on Base64Image Field.

**Comment by charlesakio** [comment]
Tested all three scenarios with the same data. All of them are not working. 
Will go through [Stackoverflow regarding Base64 ImageField](http://stackoverflow.com/questions/28036404/django-rest-framework-upload-image-the-submitted-data-was-not-a-file). 

http://stackoverflow.com/questions/32017119/put-request-for-image-upload-not-working-in-django-rest

**Comment by charlesakio** [comment]
@juliosueiras, where are we going to upload images?

**Comment by charlesakio** [comment]
Added Base64ImageField class and in logo created a fake image.
```javascript
{
    "user": {
        "email": "business@gmail.com",
        "first_name": "Charles",
        "last_name": "Javelona",
        "mobile": "123456789",
        "date_joined": "2016-08-04T10:12:13.650674Z",
        "is_profile_completed": false,
        "is_a_student": false
    },
    "logo": "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
    "company_name": "Charles",
    "industry": 0,
    "website": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Logo_TV_2015.png",
    "description": "This is a description",
    "employee_count": 3,
    "office_location": "2170 Bruns rd.",
    "office_city": "Oakville",
    "office_postal_code": "L5J4J2"
}
```

This created a different error
<img width="1280" alt="screen shot 2016-08-04 at 6 51 11 am" src="https://cloud.githubusercontent.com/assets/7959179/17399411/e7896bb8-5a0f-11e6-80a5-3a6f2b5357e0.png">
<img width="1280" alt="screen shot 2016-08-04 at 6 51 23 am" src="https://cloud.githubusercontent.com/assets/7959179/17399412/e78e15c8-5a0f-11e6-8c94-01bbbcd37313.png">

**Comment by charlesakio** [comment]
Would need [this](http://stackoverflow.com/questions/5871730/need-a-minimal-django-file-upload-example) to convert a proper "DEV environment" for static files.

**Comment by charlesakio** [comment]
UPDATE:
Tested in the admin. It seems to upload the image file.

<img width="1280" alt="screen shot 2016-08-04 at 8 32 11 am" src="https://cloud.githubusercontent.com/assets/7959179/17401865/0bbbf7c2-5a1e-11e6-9e01-0aae6b70e847.png">

Question is where is it uploaded?

**Comment by charlesakio** [comment]
Able to render the media assets. The fix is in this code. 
https://github.com/UnivJobs/univjobs-back/compare/aff7c8b3639b...117ece118d39

**Comment by charlesakio** [comment]
@juliosueiras, URL is working on my implementation.
See JSON key called "logo".
<img width="1280" alt="screen shot 2016-08-04 at 11 28 38 pm" src="https://cloud.githubusercontent.com/assets/7959179/17425420/475eaacc-5a9b-11e6-9c2e-8fe1c5067c19.png">

What is left is the actual PUT through REST.

**Comment by juliosueiras** [comment]
# Leave a comment. Trailing lines starting with '#' (like these) will be ignored,
# and empty messages will not be submitted. Comments are formatted with GitHub
# Flavored Markdown (GFM):
#
#   http://github.github.com/github-flavored-markdown
#
# On univjobs/univjobs-back issue #82
#

## Issue
- JSON does not work well with Image/File upload , hence it should use Multipart/Form-data

## Solution
### Front-end
- Use FormData for upload

#### Step 1 - HTML:
- Use `<input type="file" name="pic" accept="image/*">` or similar for uploading files
#### Step 2 - React/JS:
- Use `new FormData()` for putting all the fields(including image) as a multipart/form-data

```javascript
for (key, value in dict) {
    let form = new FormData()
    form.append(key, value)
}
```
#### Step 3 - Axios:
- Use the below snippet for axios call:
```javascript
axios.put('/api/me/', form) // <- also put JWT Token
```

### Back-end
- For django side request.data is actually a QueryDict that have all the files , so is the operation as any other, put will pass the data to serializer and it will do a update execute(which will **replace**, not overwrite, which mean that it replace the old object instance with the new object instance )
```python
    @parser_classes((MultiPartParser,))
    def put(self, request):
        request.data <= this actually contain a QueryDict including all fields including logo/image
        serializer = self.get_user_serializer(request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
```

**Comment by charlesjavelona** [comment]
@stemmlerjs, is there anything I'm doing wrong when supplying the request?

## First attempt using POSTMAN:
Here is the key and value using PUT and form-data

<img width="1280" alt="screen shot 2016-08-06 at 7 28 13 pm" src="https://cloud.githubusercontent.com/assets/7959179/17459578/462574b6-5c0c-11e6-8f13-857bea9167e4.png">

### Results:
Here are the errors thrown
```
{
  "user": [
    "This field is required."
  ],
  "website": [
    "Enter a valid URL."
  ]
}
```
Here are the **HEADERS** info
```
Connection →keep-alive
Content-Type →application/json
Date →Sat, 06 Aug 2016 23:33:27 GMT
Server →nginx
Transfer-Encoding →chunked
X-Powered-By →Express
access-control-allow-credentials →true
access-control-allow-headers →accept, content-type
access-control-allow-methods →CHECKOUT,CONNECT,COPY,DELETE,GET,HEAD,LOCK,M-SEARCH,MERGE,MKACTIVITY,MKCALENDAR,MKCOL,MOVE,NOTIFY,OPTIONS,PATCH,POST,PROPFIND,PROPPATCH,PURGE,PUT,REPORT,SEARCH,SUBSCRIBE,TRACE,UNLOCK,UNSUBSCRIBE
access-control-allow-origin →chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo
allow →GET, PUT, HEAD, OPTIONS
vary →Accept, Cookie
x-frame-options →SAMEORIGIN
x-runnable-navi-tid →76afabdc-839a-4d34-ac5a-3e5b85d5d591
```

**Comment by stemmlerjs** [comment]
One thing I noticed is that your header shows your request is of type application/Json. Shouldn't that be multipart/form data?

**Comment by charlesjavelona** [comment]
Yeah, if you look at the picture above, the button form-data is clicked.

**Comment by charlesjavelona** [comment]
## Second attempt using POSTman

### Things that were changed/added
- Defined a [put](https://github.com/UnivJobs/univjobs-back/commit/9f37263014bdde8557eb48f14873cd195f2328de) function within Employer serializer. Including the [import statements](https://github.com/UnivJobs/univjobs-back/commit/a0a7011bbc776730ec0eb44a2d15883fd41f9e49)
- Defined in the header multipart/form-data.

Here is the key and value using PUT and form-data.
Nothing was changed here.

<img width="1280" alt="screen shot 2016-08-06 at 9 28 45 pm" src="https://cloud.githubusercontent.com/assets/7959179/17459914/f77babc6-5c1c-11e6-9061-5af3969552f9.png">

### Results:
Here are the errors thrown.
Weird that keys website and user switched.
```
{
  "website": [
    "Enter a valid URL."
  ],
  "user": [
    "This field is required."
  ]
}
```

Here are the **HEADERS** info

```
Connection →keep-alive
Content-Type →application/json
Date →Sun, 07 Aug 2016 01:23:09 GMT
Server →nginx
Transfer-Encoding →chunked
X-Powered-By →Express
access-control-allow-credentials →true
access-control-allow-headers →accept, content-type
access-control-allow-methods →CHECKOUT,CONNECT,COPY,DELETE,GET,HEAD,LOCK,M-SEARCH,MERGE,MKACTIVITY,MKCALENDAR,MKCOL,MOVE,NOTIFY,OPTIONS,PATCH,POST,PROPFIND,PROPPATCH,PURGE,PUT,REPORT,SEARCH,SUBSCRIBE,TRACE,UNLOCK,UNSUBSCRIBE
access-control-allow-origin →chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo
allow →GET, PUT, HEAD, OPTIONS
vary →Accept, Cookie
x-frame-options →SAMEORIGIN
x-runnable-navi-tid →dd90c1bb-7464-491a-ab86-7eedd73018a1
```

### Headers
<img width="1280" alt="screen shot 2016-08-06 at 9 39 40 pm" src="https://cloud.githubusercontent.com/assets/7959179/17459960/5af2849e-5c1e-11e6-87fe-6d663d4bf769.png">

**Comment by charlesjavelona** [comment]
Oh wait, something changed. Hold on, there was a typo in the headers.

Here is the new error.
```
{
  "detail": "Multipart form parse error - Invalid boundary in multipart: None"
}
```

**Comment by charlesjavelona** [comment]
Reference to this 
http://www.mm1886.com/0508/put-request-for-image-upload-not-working-in-django-rest/

**Comment by stemmlerjs** [comment]
Just setup the PUT to ```/api/me``` in React/Redux using Axios as @juliosueiras had instructed earlier to use FormData to send a multipart formdata request.

For the employer PUT, I'm consistently getting a 500 Error from the server reporting the response of 

```javascript
{
     detail: "school field require"
}
```

Haven't tested it out with the Student PUT as we haven't yet implemented that screen.

@juliosueiras, you can take a look at the code that I'm using to submit the form in a function called **employerProfilePUT** which is called by **submitProfileFirstTime** that passes in the objects for the request.

```javascript
// This is the large JSON object that gets sent
var putData = {
  is_a_student: false,
  is_profile_completed: true, // set this flag to true so we know for next time
  company_name: profileInfo.companyName,
  logo: profileInfo.logoUrl,
  office_location: profileInfo.officeAddress,
  office_city: profileInfo.officeCity,
  office_postal_code: profileInfo.officePostalCode,
  description: profileInfo.description,
  website: profileInfo.website,
  employee_count: profileInfo.employeeCount,
  industry: profileInfo.industry.id,
  date_joined: user.dateJoined,
  first_name: user.firstName,
  last_name: user.lastName,
  email: user.email
}

employerProfilePUT(putData)
```

And here is the actual request. Notice that by not using 'multipart/form-data' in the header for the request, the arbitrary boundary text is automatically supplied by the browser into the request.

```javascript
// helpers/profile.js

import axios from 'axios'
import config from 'config'
import { getAccessToken } from 'helpers/auth'

export function employerProfilePUT(data) {
  let formData = new FormData();
  const accessToken = getAccessToken();

  for(let key in data) {
    formData.append(key, data[key])
  }

  return axios({
    method: 'put',
    url: config.baseUrl + 'me/',
    headers: {
      "Authorization": "JWT " + accessToken
    },
    data: formData
  })
```

Let me know if I'm doing something blaringly wrong please dudes.

See commit here: https://github.com/UnivJobs/univjobs-front/commit/f80e1b0488490be42786f5f58200304f21a824a1

**Comment by charlesjavelona** [comment]
This one has been done awhile back.
