### ISSUE TITLE
Employer Profile Screen Changes

### ISSUE THREAD

**Issue by stemmlerjs** [UnivJobs/univjobs-back#84]
# Employer Profile Screen
Some of the fields we have on the screen right now. The fields that I've written CONCERNS about are things I think we should address.

### Company Name
	- @return String
	- the name of the company

### Industry Field
	- @return Number OR String
	- When return value is a number, this is the ID of the Industry
	- When the return value is a string, this is the name of the new industry to be added
	
	CONCERNS
	- I was rethinking the user's ability to be able to create a new Industry Name. Perhaps we should just inform
	the user to send us an email so we can add their industry. While we can perform Regex and ensure that the 
	industry name is in fact an alphabetical sequence of word(s), we don't want people to make rude industry names
	that will show up for all users that sign up later.
	We could also just have it setup so that the names have to be approved before they're visible but then that's just more
	work on us. Let me know what you want to do.
	
### Website
	- @return String
	- website name

### Description
	- @return String
	- company description

### EmployeeCount
	- @return String 
	- employee count
	
	CONCERNS
	- I was thinking that this should be a CHOICE field instead. Like, lets do:
		choices
		- < 10
		- 10 to 50
		- 50+
        ie: radio button

     This will result in us having an additonal list to create in /api/lists/{choice}
### Office Location
	- @return String
	- Example: "Silicon Valley, California".
	
	CONCERNS
	- I know that we discussed earlier that we want to have postal code, city and province/state.
	Currently, we just have a basic string field with no form.
	Do we want:
	 - 3 new fields on screen (postal code, city, province/state). Ie: driopdowns.
	 - or keep it like this, free form String field as it is in invision. Ie: input fields.

**Comment by charlesjavelona** [comment]
# Employer Profile Screen
Some of the fields we have on the screen right now. The fields that I've written CONCERNS about are things I think we should address.

### Company Name
	- @return String
	- the name of the company

**Input on company**
- This returns a string already.


### Industry Field
	- @return Number OR String
	- When return value is a number, this is the ID of the Industry
	- When the return value is a string, this is the name of the new industry to be added
	
	CONCERNS
	- I was rethinking the user's ability to be able to create a new Industry Name. Perhaps we should just inform
	the user to send us an email so we can add their industry. While we can perform Regex and ensure that the 
	industry name is in fact an alphabetical sequence of word(s), we don't want people to make rude industry names
	that will show up for all users that sign up later.
	We could also just have it setup so that the names have to be approved before they're visible but then that's just more
	work on us. Let me know what you want to do.

**Input on the industry**
- We can have the employers email us to add the new industry.	

### Website
	- @return String
	- website name
**Input on website**
- Website does return a string

### Description
	- @return String
	- company description
**Input on description**
- Description does return a string 

### EmployeeCount
	- @return String 
	- employee count

	CONCERNS
	- I was thinking that this should be a CHOICE field instead. Like, lets do:
		choices
		- < 10
		- 10 to 50
		- 50+
     This will result in us having an additonal list to create in /api/lists/{choice}
**Input on EmployeeCount**
- We have to make the number > 1, because we want small businesses and startups to be able to post jobs as well.



### Office Location
	- @return String
	- Example: "Silicon Valley, California".
	
	CONCERNS
	- I know that we discussed earlier that we want to have postal code, city and province/state.
	Currently, we just have a basic string field with no form.
	Do we want:
	 - 3 new fields on screen (postal code, city, province/state)
	 - or keep it like this, free form String field as it is in invision.
**Input on Location**
- The new fields are added already at the back.

## Reference for the inputs
- https://github.com/UnivJobs/univjobs-back/blob/develop/univjobs/employer/models.py

**Comment by stemmlerjs** [comment]
**EmployeeCount**
- we've confirmed that this will be an input field that expects an integer greater than 1.

**Comment by stemmlerjs** [comment]
**Industry**
- We've confirmed that we will just leave a message prompting the user to email us if their industry is not there.

**Comment by stemmlerjs** [comment]
**Office Location**
- We've confirmed that we are going to change Office Location to be Office Address.
- We've also confirmed that we need to add Office City as an additional text field.
- We've also confirmed that we need to add Office Postal Code as an additional text field.
