### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by stemmlerjs** [UnivJobs/univjobs-back#87]
For ```api/job/new```,
remove the following fields:

- **postal_code (string),**
- **province (choice) = ['AB' or 'BC' or 'MB' or 'NB' or 'NL' or 'NS' or 'ON' or 'QC' or 'PE' or 'SK'],**

On ```api/me/``` for the student profile,
When performing a PUT, please make the following fields non-required:

- **resume**

**Comment by charlesjavelona** [comment]
Closed #87
