### ISSUE TITLE
Fix /job/new/

### ISSUE THREAD

**Issue by charlesjavelona** [UnivJobs/univjobs-back#88]
- Ensure that this API endpoint is working both on Django Rest and via direct API call.

Doing - Charles

**Comment by charlesjavelona** [comment]
Repeating the steps for tomorrow when debugging.

- ssh to aws
- inside univjobs/,  type 'python34 manage.py runserver 0.0.0.0:8000'
- make sure to have the import ipdb and ipdb.set_trace() on top of the assumed bug line.

**Comment by stemmlerjs** [comment]
![image](https://cloud.githubusercontent.com/assets/6892666/18679994/d54a6390-7f2f-11e6-8d78-e4f400f25fad.png)

Also make sure to return a valid error message when invalid input is supplied. Currently, it just hangs.

**Comment by stemmlerjs** [comment]
Probably part of this issue,

Django Rest is not letting me use the /api/job/new/ page even after authenticating.

![image](https://cloud.githubusercontent.com/assets/6892666/18680145/7f2b0072-7f30-11e6-9ba8-bfb93ef68aaa.png)

**Comment by charlesjavelona** [comment]
@juliosueiras, could you please check on this one. Im not familiar with the new auth.
Working on the error that @stemmlerjs has.

@stemmlerjs, couple of things I need you to change.
  - **type** needs to be an int.
  - **paid** needs to be an int. 
        - 0 for paid, 1 for unpaid.

**Comment by charlesjavelona** [comment]
DB integrity error:

<img width="1280" alt="screen shot 2016-09-21 at 10 15 29 pm" src="https://cloud.githubusercontent.com/assets/7959179/18735086/03abbcec-8049-11e6-8b3c-91b86c6a4f55.png">

**Comment by charlesjavelona** [comment]
@stemmlerjs , here is some notes on how to move forward.

**To avoid CSRF token error in the front-end dev:**
 - Use Incognito Browser for localhost

**Comment by charlesjavelona** [comment]
@juliosueiras, here is another error in the db

<img width="1280" alt="screen shot 2016-09-22 at 7 19 24 am" src="https://cloud.githubusercontent.com/assets/7959179/18746388/16abbe72-8095-11e6-8bd7-54ab58d2f81a.png">

**Comment by charlesjavelona** [comment]
Based on prior research, migration of the new models might be the issue.
Here is the develop branch migration code.

https://github.com/UnivJobs/univjobs-back/blob/develop/univjobs/job/migrations/0001_initial.py

**Comment by stemmlerjs** [comment]
1.) Still getting errors when I try to create a resource via POSTman

![image](https://cloud.githubusercontent.com/assets/6892666/18758240/392609d2-80c5-11e6-9891-7b0e8c33a8cd.png)
![image](https://cloud.githubusercontent.com/assets/6892666/18758255/4bdf5e66-80c5-11e6-8506-40d296bbd8a0.png)


2.) Still getting ```{"detail":"CSRF Failed: CSRF token missing or incorrect."}``` when requesting through the application.
![image](https://cloud.githubusercontent.com/assets/6892666/18758331/91998f9e-80c5-11e6-9dcf-bfe5c079945d.png)

![image](https://cloud.githubusercontent.com/assets/6892666/18758354/b81993f8-80c5-11e6-90c4-c0da51548b8a.png)

**Comment by charlesjavelona** [comment]
Could you change paid to a boolean 0 or 1?

**Comment by charlesjavelona** [comment]
@juliosueiras, this might solve that problem that @stemmlerjs has.
http://stackoverflow.com/questions/18571157/best-way-to-add-additional-fields-to-django-rest-framework-modelviewset-when-cre

**Comment by charlesjavelona** [comment]
Able to create a job by migrating current models.
Please see pic:
<img width="1280" alt="screen shot 2016-09-22 at 10 46 26 pm" src="https://cloud.githubusercontent.com/assets/7959179/18772623/7de7093a-8116-11e6-927d-96bf86181bc3.png">

**Comment by charlesjavelona** [comment]
Here is the current error: 

<img width="1280" alt="screen shot 2016-09-24 at 1 20 27 pm" src="https://cloud.githubusercontent.com/assets/7959179/18810022/c45a8560-8259-11e6-8b90-cc534ea357d5.png">

**Comment by charlesjavelona** [comment]
Getting these errors @stemmlerjs,

<img width="1280" alt="screen shot 2016-09-24 at 2 36 00 pm" src="https://cloud.githubusercontent.com/assets/7959179/18810440/43db99dc-8264-11e6-9a73-63cd432e0c99.png">

**Comment by charlesjavelona** [comment]
Was able to create a new job multiple times. Error was thrown before when jobType was set to 1.
Now its 0, other notes was that there were other choices created in the choices.py 

Will test to see if I set jobType to 1.

**Comment by charlesjavelona** [comment]
It seems that I can now create multiple jobs.
What seems to change was the addition of choices.py
Now, please see the following choices.py

```
JOB_TYPE = (
    (0, 'One-time Gig'),
    (1, 'Summer 2017'),
    (2, 'Winter Break'),
    (3, 'Freelancing'),
    (4, 'Campus Rep & Brand Ambassador'),
    (5, 'Part-time work'),
)
```

@stemmlerjs, could you pass the associated number to the type of job the employer clicks?

**Comment by charlesjavelona** [comment]
Done
