### ISSUE TITLE
Regular Browser view returns a CSRF error.

### ISSUE THREAD

**Issue by charlesjavelona** [UnivJobs/univjobs-back#92]
For the past few days, we have been dealing with the CSRF issue. 
This issue can be repeated through:
- Regular browser request
- POSTMAN request 

The following steps are our workaround:
- Incognito mode 
- command line HTTP request
- Adding the token manually to the POSTMAN request

@juliosueiras,  could we please get the following:
- Research & explain as to why this is happening
- Make the regular browser request work

**Comment by juliosueiras** [comment]
This issue occur at the front-end due to missing X-CSRFToken header option in some POST/PATCH/PUT axios call

**BEFORE:**
```js
  return axios({
    method: 'post',
    url: config.baseUrl + 'login/',
    headers: {
      "content-type": "application/json"
    },
    data: JSON.stringify(bodyData)
  })
}
```

**AFTER:**
```js
  const csrfToken = getCSRFToken();

....code in between

  return axios({
    method: 'post',
    url: config.baseUrl + 'login/',
    headers: {
      "content-type": "application/json",
      'X-CSRFToken': csrfToken
    },
    data: JSON.stringify(bodyData)
  })
}
```

This is apply to all post/put/patch call

**Comment by charlesjavelona** [comment]
@juliosueiras,

You also forgot to add in some cases that commenting out the following in settings.py helps

```python
# CORS_ORIGIN_ALLOW_ALL = False
# CORS_ALLOW_CREDENTIALS = True
# CORS_ORIGIN_WHITELIST = (
#     'http://localhost:3000',
#     'https://localhost:8080'
# )

# CORS_REPLACE_HTTPS_REFERER = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True

#CSRF_TRUSTED_ORIGINS=['https://localhost:8080/']
```
