### ISSUE TITLE
Ansible [and Docker?] testing

### ISSUE THREAD

**Issue by charlesjavelona** [UnivJobs/univjobs-back#94]
We need to be able to spin up an EC2 instance from scratch and deploy our application on it.
We mostly need this so that we can easily use new instances for testing out new features without having to break our existing development environment.

The Ansible config should:
- install all dependencies including python and pip
- download all requirements and resolve all dependencies that the requirements.txt file relies on

At the end of the script, we should be able to run the brand new Univjobs environment.

If it makes it easier for you to deploy and containerize the application, maybe use Docker (although this will need to be setup as a dependencies).

**Comment by juliosueiras** [comment]
Got most ansible things working , stuck at the point of launching react code(as bundle) in part with django
error is `Invariant Violation _registerComponent(...): Target container is not a DOM element.` but not able to get the exact line number yet, still try to unminify and unglify the code

**Comment by charlesjavelona** [comment]
@juliosueiras , could you explain the problem & how you got to the solution?

**Comment by juliosueiras** [comment]
Solution:
fix is at a1e9fe98b9f71e0ad31dac5ab3546a909b8a8da0

The issue is due to root app dom element.

***Before:***
```js
<div id="react-app"></div>
```

***After:***
```js
<div id="app"></div>
```
